providers = ["node"]

[phases.install]
cmds = [
    "npm install -g corepack",
    "corepack enable",
    "corepack prepare pnpm@9.14.2 --activate",
    "pnpm install"
]

[phases.build]
cmds = [
    "pnpm --filter @bajo-olymbyx/app build"
]

[start]
cmd = "pnpm --filter @bajo-olymbyx/app start"
