providers = ["node"]

[phases.install]
cmds = [
    "npm install -g corepack",
    "corepack enable",
    "corepack prepare pnpm@9.4.0 --activate",
    "pnpm install"
]

[phases.build]
cmds = [
    "pnpm --filter @bajo-olymbyx/app generate"
]

[start]
cmd = "pnpm --filter @bajo-olymbyx/app start:generate"